#Gladiator Spawn Locations
gravesPluginName: graves v2.8.9 (MC 1.20-1.20.2).zip
spawnLocations:
  player1:
    x: 1
    y: 80
    z: 1
  player2:
    x: 2
    y: 80
    z: 2
  audience:
    x: 3
    y: 80
    z: 3
#Doors must be the same width/height.
doorWidth: 5
doorHeight: 4
#This is the center block of the BOTTOM row!
doorLocations:
  centerBottomDoor1:
    x: 3
    y: 73
    z: -84
  centerBottomDoor2:
    x: 3
    y: 73
    z: -87